#ifndef __LOGIC_SKILL_EVTDEF_H__
#define __LOGIC_SKILL_EVTDEF_H__
#include "basedef.h"
namespace SKILLEDITOR
{
#define MAX_SEQ 8
	enum EModifierOnAuraApplyTime
	{
		EMODIFY_AURA_TIMEINVALID = -1,
		EMODIFY_AURA_TIMEONAPPEND,
		EMODIFY_AURA_TIMEONREMOVE,
		EMODIFY_AURA_TIMECOUNT
	};
	enum EModifierOnEotApplyTime
	{
		EMODIFY_EOT_TIMEINVALID = -1,
		EMODIFY_EOT_TIMEONAPPEND,
		EMODIFY_EOT_TIMEONTIRGGER,
		EMODIFY_EOT_TIMEONREMOVE,
		EMODIFY_EOT_TIMECOUNT,
	};
	enum EAttrModifierType
	{
		EATTR_MODIFY_TYPE_INVALID = -1,
		EATTR_MODIFY_TYPE_CHAR,
		EATTR_MODIFY_TYPE_SPELL,
		EATTR_MODIFY_TYPE_BULLET,
		EATTR_MODIFY_TYPE_AURA,
		EATTR_MODIFY_TYPE_EOT,
		EATTR_MODIFY_TYPE_COUNT
	};

	inline void SplitSeqKey(BSLib::s32 key, BSLib::s32 &type, BSLib::s32 &idx)
	{
		type = (key & 0x0f000000) >> 24;
		idx = key & 0x00ffffff;
	}
}
#endif